# Site settings
title: Vident
email: vident.geotech@gmail.com
description: Vident.ai website Remote sensing analytics and exploaitation > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vident.ai" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
